CREATE TABLE [dbo].[GeoData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GeoSpatialDataId] [int] NOT NULL,
	[GeoObjectDescription] [text] NOT NULL,
	[GeoObjectType] [int] NOT NULL,
	[HoleId] [int] NOT NULL,
	[OrderNumber] [int] NOT NULL,
	[CourseId] [int] NULL,
 CONSTRAINT [PK__GeoData__3214EC077F60ED59] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

