<?xml version="1.0" encoding="utf-8"?><Database Name="GolfDB20161207-01" Class="GolfDB2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-S7JQFF1\SQLEXPRESS;Initial Catalog=GolfDB20161207-01;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GolfDB20161207_01ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TeeTime" Member="TeeTimes">
    <Type Name="TeeTime">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeeTimeOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tee_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservedByName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TelephoneNumber" Type="System.String" DbType="NChar(80)" CanBeNull="true" />
      <Column Name="HoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfPlayers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerNames" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="TeeTime_TeeTime" Member="TeeTime2" ThisKey="Id" OtherKey="Id" Type="TeeTime" Cardinality="One" />
      <Association Name="TeeTime_TeeTimeDetail" Member="TeeTimeDetails" ThisKey="Id" OtherKey="TeeTimeId" Type="TeeTimeDetail" />
      <Association Name="TeeTime_TeeTime" Member="TeeTime1" ThisKey="Id" OtherKey="Id" Type="TeeTime" IsForeignKey="true" />
      <Association Name="Hole_TeeTime" Member="Hole" ThisKey="HoleId" OtherKey="Id" Type="Hole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hole" Member="Holes">
    <Type Name="Hole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhotoUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Hole_TeeTime" Member="TeeTimes" ThisKey="Id" OtherKey="HoleId" Type="TeeTime" />
      <Association Name="Hole_ScoreEntry" Member="ScoreEntries" ThisKey="Id" OtherKey="HoleId" Type="ScoreEntry" />
      <Association Name="Hole_EventDetail" Member="EventDetails" ThisKey="Id" OtherKey="StartHoleId" Type="EventDetail" />
    </Type>
  </Table>
  <Table Name="dbo.HoleList" Member="HoleLists">
    <Type Name="HoleList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="HoleList" Member="HoleList1" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="BList" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="HoleList_EventDetail" Member="EventDetails" ThisKey="Id" OtherKey="PlayListId" Type="EventDetail" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalSettings" Member="GlobalSettings">
    <Type Name="GlobalSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SettingName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LastWritten" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="LastUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ScoreCard" Member="ScoreCards">
    <Type Name="ScoreCard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartingHole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Names" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TeeTimeDetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ScoreCard_ScoreEntry" Member="ScoreEntries" ThisKey="Id" OtherKey="ScoreCardId" Type="ScoreEntry" />
      <Association Name="Event_ScoreCard" Member="Event" ThisKey="EventId" OtherKey="id" Type="Event" IsForeignKey="true" />
      <Association Name="TeeTimeDetail_ScoreCard" Member="TeeTimeDetail" ThisKey="TeeTimeDetailId" OtherKey="Id" Type="TeeTimeDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[end]" Member="end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Event_ScoreCard" Member="ScoreCards" ThisKey="id" OtherKey="EventId" Type="ScoreCard" />
      <Association Name="Event_ScoreEntry" Member="ScoreEntries" ThisKey="id" OtherKey="EventId" Type="ScoreEntry" />
      <Association Name="Event_EventDetail" Member="EventDetails" ThisKey="id" OtherKey="EventId" Type="EventDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TeeTimeDetail" Member="TeeTimeDetails">
    <Type Name="TeeTimeDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AmountPaid" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TeeTimeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Skins" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TeeTimeDetail_ScoreCard" Member="ScoreCards" ThisKey="Id" OtherKey="TeeTimeDetailId" Type="ScoreCard" />
      <Association Name="TeeTime_TeeTimeDetail" Member="TeeTime" ThisKey="TeeTimeId" OtherKey="Id" Type="TeeTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScoreEntry" Member="ScoreEntries">
    <Type Name="ScoreEntry" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreCardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ordinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_ScoreEntry" Member="Event" ThisKey="EventId" OtherKey="id" Type="Event" IsForeignKey="true" />
      <Association Name="Hole_ScoreEntry" Member="Hole" ThisKey="HoleId" OtherKey="Id" Type="Hole" IsForeignKey="true" />
      <Association Name="ScoreCard_ScoreEntry" Member="ScoreCard" ThisKey="ScoreCardId" OtherKey="Id" Type="ScoreCard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventDetail" Member="EventDetails">
    <Type Name="EventDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfHoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsShotgunStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sponsor" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PlayListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrgId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartHoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumGroups" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPerGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOn" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="SkinsAmount" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfFlights" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_EventDetail" Member="Event" ThisKey="EventId" OtherKey="id" Type="Event" IsForeignKey="true" />
      <Association Name="HoleList_EventDetail" Member="HoleList" ThisKey="PlayListId" OtherKey="Id" Type="HoleList" IsForeignKey="true" />
      <Association Name="Hole_EventDetail" Member="Hole" ThisKey="StartHoleId" OtherKey="Id" Type="Hole" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.IsScoreEntrySkin" Method="IsScoreEntrySkin">
    <Parameter Name="eventId" Type="System.Int32" DbType="Int" />
    <Parameter Name="HoleId" Parameter="holeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="IsScoreEntrySkinResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreCardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ordinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.IsScoreEntrySkin" Method="IsScoreEntrySkin1">
    <Parameter Name="eventId" Type="System.Int32" DbType="Int" />
    <Parameter Name="HoleId" Parameter="holeId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>