<?xml version="1.0" encoding="utf-8"?><Database Name="GolfDB20161207-01" Class="TeeTimeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-S7JQFF1\SQLEXPRESS;Initial Catalog=GolfDB20161207-01;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GolfDB20161207_01ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TeeTime" Member="TeeTimes">
    <Type Name="TeeTime">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeeTimeOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tee_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservedByName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TelephoneNumber" Type="System.String" DbType="NChar(80)" CanBeNull="true" />
      <Column Name="HoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfPlayers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerNames" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="TeeTime_TeeTime" Member="TeeTime2" ThisKey="Id" OtherKey="Id" Type="TeeTime" Cardinality="One" />
      <Association Name="TeeTime_TeeTime" Member="TeeTime1" ThisKey="Id" OtherKey="Id" Type="TeeTime" IsForeignKey="true" />
    </Type>
  </Table>
</Database>